---
# General variables

# The base stack name, change this if you want to deploy multiple instances on the same host.
mautic_instance_name: mautic

# Set this to true to enable logging even of possible sensitive information
mautic_setup_force_log: false

# Set this to true to force container pull on every mautic_setup_all run
# Hint: mautic_update already enforces container pull on every run
mautic_force_container_pull: false

# Mautic application settings
mautic_install_source: "docker"
mautic_trusted_proxies: '["127.0.0.1"]'
mautic_site_url: "http://{{ mautic_instance_name }}.local:{{ mautic_httpd_port }}"
# Database settings
mautic_db_driver: "pdo_mysql"
mautic_db_table_prefix: ""
mautic_db_name: "{{ mautic_instance_name }}"
mautic_db_user: "{{ mautic_instance_name }}"
mautic_db_user_secret: my_secret
mautic_db_root_secret: my_secret

# Docker networks
mautic_network_backend: "{{ mautic_instance_name }}-net"
# ToDo: traefik network should be defined elsewhere
mautic_network_frontend: "traefik_dev_network"

# Mautic service container
mautic_app_image_name: "ghcr.io/netresearch/mautic"
mautic_app_image_tag: "4.2-php7.4"
mautic_app_storage_container: "/var/www/html"
mautic_app_env:
  MAUTIC_DB_HOST: "{{ mautic_dbms_service_name }}"
  MAUTIC_DB_USER: "{{ mautic_db_user }}"
  MAUTIC_DB_PASSWORD: "{{ mautic_db_user_secret }}"
  MAUTIC_DB_NAME: "{{ mautic_db_name }}"
  MAUTIC_INSTALL_SOURCE: "{{ mautic_install_source }}"
  MAUTIC_DB_DRIVER: "{{ mautic_db_driver }}"
  MAUTIC_DB_TABLE_PREFIX: "{{ mautic_db_table_prefix }}"
  MAUTIC_TRUSTED_PROXIES: "{{ mautic_trusted_proxies | string }}"
  MAUTIC_SITE_URL: "{{ mautic_site_url }}"

# HTTPD service
mautic_httpd_image_name: "{{ mautic_app_image_name }}"
mautic_httpd_image_tag: "{{ mautic_app_image_tag }}"
mautic_httpd_port: "80"
mautic_httpd_labels:

# DBMS service container
mautic_dbms_image_name: "mariadb"
mautic_dbms_image_tag: "10"
mautic_dbms_storage_container: "/var/lib/mysql"
mautic_dbms_env:
  MARIADB_DATABASE: "{{ mautic_db_name }}"
  MARIADB_USER: "{{ mautic_db_user }}"
  MARIADB_ROOT_PASSWORD: "{{ mautic_db_root_secret }}"
  MARIADB_PASSWORD: "{{ mautic_db_user_secret }}"

# Cron service container
mautic_cron_image_name: "ghcr.io/premoweb/chadburn"
mautic_cron_image_tag: "latest"
mautic_cron_service_command: "daemon"

mautic_console: "php {{ mautic_app_storage_container }}/bin/console --no-ansi --no-interaction"

mautic_app_labels:
  chadburn.enabled: "true"
  chadburn.job-exec.{{ mautic_instance_name }}_segments_update.schedule: "8,23,38,52 * * * *"
  chadburn.job-exec.{{ mautic_instance_name }}_segments_update.command:
    "{{ mautic_console }} mautic:segments:update"
  chadburn.job-exec.{{ mautic_instance_name }}_segments_update.user: "www-data"
  chadburn.job-exec.{{ mautic_instance_name }}_import.schedule: "*/5 * * * *"
  chadburn.job-exec.{{ mautic_instance_name }}_import.command:
    "{{ mautic_console }} mautic:import"
  chadburn.job-exec.{{ mautic_instance_name }}_import.user: "www-data"
  chadburn.job-exec.{{ mautic_instance_name }}_campaigns_update.schedule: "5,20,35,50 * * * *"
  chadburn.job-exec.{{ mautic_instance_name }}_campaigns_update.command:
    "{{ mautic_console }} mautic:campaigns:update"
  chadburn.job-exec.{{ mautic_instance_name }}_campaigns_update.user: "www-data"
  chadburn.job-exec.{{ mautic_instance_name }}_campaigns_trigger.schedule: "2,17,32,47 * * * *"
  chadburn.job-exec.{{ mautic_instance_name }}_campaigns_trigger.command:
    "{{ mautic_console }} mautic:campaigns:trigger"
  chadburn.job-exec.{{ mautic_instance_name }}_campaigns_trigger.user: "www-data"
  chadburn.job-exec.{{ mautic_instance_name }}_messages_send.schedule: "0,15,30,45 * * * *"
  chadburn.job-exec.{{ mautic_instance_name }}_messages_send.command:
    "{{ mautic_console }} mautic:messages:send"
  chadburn.job-exec.{{ mautic_instance_name }}_messages_send.user: "www-data"
  chadburn.job-exec.{{ mautic_instance_name }}_emails_send.schedule: "0,15,30,45 * * * *"
  chadburn.job-exec.{{ mautic_instance_name }}_emails_send.command:
    "{{ mautic_console }} mautic:emails:send"
  chadburn.job-exec.{{ mautic_instance_name }}_emails_send.user: "www-data"
  chadburn.job-exec.{{ mautic_instance_name }}_email_fetch.schedule: "0,15,30,45 * * * *"
  chadburn.job-exec.{{ mautic_instance_name }}_email_fetch.command:
    "{{ mautic_console }} mautic:email:fetch"
  chadburn.job-exec.{{ mautic_instance_name }}_email_fetch.user: "www-data"
  chadburn.job-exec.{{ mautic_instance_name }}_social_monitoring.schedule: "0,15,30,45 * * * *"
  chadburn.job-exec.{{ mautic_instance_name }}_social_monitoring.command:
    "{{ mautic_console }} mautic:social:monitoring"
  chadburn.job-exec.{{ mautic_instance_name }}_social_monitoring.user: "www-data"
  chadburn.job-exec.{{ mautic_instance_name }}_webhooks_process.schedule: "0,15,30,45 * * * *"
  chadburn.job-exec.{{ mautic_instance_name }}_webhooks_process.command:
    "{{ mautic_console }} mautic:webhooks:process"
  chadburn.job-exec.{{ mautic_instance_name }}_webhooks_process.user: "www-data"
  chadburn.job-exec.{{ mautic_instance_name }}_broadcasts_send.schedule: "0,15,30,45 * * * *"
  chadburn.job-exec.{{ mautic_instance_name }}_broadcasts_send.command:
    "{{ mautic_console }} mautic:broadcasts:send"
  chadburn.job-exec.{{ mautic_instance_name }}_broadcasts_send.user: "www-data"
  chadburn.job-exec.{{ mautic_instance_name }}_maintenance_cleanup.schedule: "* 1 * * *"
  chadburn.job-exec.{{ mautic_instance_name }}_maintenance_cleanup.command:
    "{{ mautic_console }} mautic:maintenance:cleanup --days-old=365"
  chadburn.job-exec.{{ mautic_instance_name }}_maintenance_cleanup.user: "www-data"
  chadburn.job-exec.{{ mautic_instance_name }}_iplookup_download.schedule: "0 4 15 * *"
  chadburn.job-exec.{{ mautic_instance_name }}_iplookup_download.command:
    "{{ mautic_console }} mautic:iplookup:download"
  chadburn.job-exec.{{ mautic_instance_name }}_iplookup_download.user: "www-data"
  chadburn.job-exec.{{ mautic_instance_name }}_reports_scheduler.schedule: "*/5 * * * *"
  chadburn.job-exec.{{ mautic_instance_name }}_reports_scheduler.command:
    "{{ mautic_console }} mautic:reports:scheduler"
  chadburn.job-exec.{{ mautic_instance_name }}_reports_scheduler.user: "www-data"
  chadburn.job-exec.{{ mautic_instance_name }}_unusedip_delete.schedule: "0 5 10 * *"
  chadburn.job-exec.{{ mautic_instance_name }}_unusedip_delete.command:
    "{{ mautic_console }} mautic:unusedip:delete"
  chadburn.job-exec.{{ mautic_instance_name }}_unusedip_delete.user: "www-data"
  # ENABLES HUBSPOT CRON
  # chadburn.job-exec.{{ mautic_instance_name }}_hubspot_integration_fetchleads.schedule:
  #   "10,40 * * * *"
  # chadburn.job-exec.{{ mautic_instance_name }}_hubspot_integration_fetchleads.command: >
  #   {{ mautic_console }}
  #   mautic:integration:fetchleads --integration=Hubspot
  # chadburn.job-exec.{{ mautic_instance_name }}_hubspot_integration_fetchleads.user: "www-data"
  # chadburn.job-exec.{{ mautic_instance_name }}_hubspot_integration_pushactivity.schedule:
  #   "15,45 * * * *"
  # chadburn.job-exec.{{ mautic_instance_name }}_hubspot_integration_pushactivity.command: >
  #   {{ mautic_console }}
  #   mautic:integration:pushactivity --integration=Hubspot"
  # chadburn.job-exec.{{ mautic_instance_name }}_hubspot_integration_pushactivity.user: "www-data"
  # ENABLES SALESFORCE CRON
  # chadburn.job-exec.{{ mautic_instance_name }}_salesforce_integration_fetchleads.schedule:
  #   "10,40 * * * *"
  # chadburn.job-exec.{{ mautic_instance_name }}_salesforce_integration_fetchleads.command: >
  #   {{ mautic_console }}
  #   mautic:integration:fetchleads --integration=Salesforce"
  # chadburn.job-exec.{{ mautic_instance_name }}_salesforce_integration_fetchleads.user: "www-data"
  # chadburn.job-exec.{{ mautic_instance_name }}_salesforce_integration_pushactivity.schedule:
  #   "12,42 * * * *"
  # chadburn.job-exec.{{ mautic_instance_name }}_salesforce_integration_pushactivity.command: >
  #   {{ mautic_console }}
  #   mautic:integration:pushactivity --integration=Salesforce"
  # chadburn.job-exec.{{ mautic_instance_name }}_salesforce_integration_pushactivity.user: "www-data"
  # chadburn.job-exec.{{ mautic_instance_name }}_salesforce_integration_pushleadactivity.schedule:
  #   "14,44 * * * *"
  # chadburn.job-exec.{{ mautic_instance_name }}_salesforce_integration_pushleadactivity.command: >
  #   {{ mautic_console }}
  #   mautic:integration:pushleadactivity --integration=Salesforce"
  # chadburn.job-exec.{{ mautic_instance_name }}_salesforce_integration_pushleadactivity.user: "www-data"
  # chadburn.job-exec.{{ mautic_instance_name }}_salesforce_integration_synccontacts.schedule:
  #   "16,46 * * * *"
  # chadburn.job-exec.{{ mautic_instance_name }}_salesforce_integration_synccontacts.command: >
  #   {{ mautic_console }}
  #   mautic:integration:synccontacts --integration=Salesforce"
  # chadburn.job-exec.{{ mautic_instance_name }}_salesforce_integration_synccontacts.user: "www-data"
  # ENABLES SUGARCRM CRON
  # chadburn.job-exec.{{ mautic_instance_name }}_sugarcrm_integration_fetchleads.schedule:
  #   "10,40 * * * *"
  # chadburn.job-exec.{{ mautic_instance_name }}_sugarcrm_integration_fetchleads.command: >
  #   {{ mautic_console }}
  #   mautic:integration:fetchleads --fetch-all --integration=Sugarcrm"
  # chadburn.job-exec.{{ mautic_instance_name }}_sugarcrm_integration_fetchleads.user: "www-data"
  # ENABLES PIPEDRIVE CRON
  # chadburn.job-exec.{{ mautic_instance_name }}_pipedrive_integration_fetch.schedule:
  #   "10,40 * * * *"
  # chadburn.job-exec.{{ mautic_instance_name }}_pipedrive_integration_fetch.command:
  #   "{{ mautic_console }} mautic:integration:pipedrive:fetch"
  # chadburn.job-exec.{{ mautic_instance_name }}_pipedrive_integration_fetch.user: "www-data"
  # chadburn.job-exec.{{ mautic_instance_name }}_pipedrive_integration_push.schedule:
  #   "15,45 * * * *"
  # chadburn.job-exec.{{ mautic_instance_name }}_pipedrive_integration_push.command:
  #   "{{ mautic_console }} mautic:integration:pipedrive:push"
  # chadburn.job-exec.{{ mautic_instance_name }}_pipedrive_integration_push.user: "www-data"
  # ENABLES ZOHO CRON
  # chadburn.job-exec.{{ mautic_instance_name }}_zohocrm_integration_fetchleads.schedule:
  #   "10,40 * * * *"
  # chadburn.job-exec.{{ mautic_instance_name }}_zohocrm_integration_fetchleads.command:
  #   "{{ mautic_console }} mautic:integration:fetchleads --integration=Zoho"
  # chadburn.job-exec.{{ mautic_instance_name }}_zohocrm_integration_fetchleads.user: "www-data"
  # ENABLES DYNAMICS CRON
  # chadburn.job-exec.{{ mautic_instance_name }}_dynamicscrm_integration_fetchleads.schedule:
  #   "10,40 * * * *"
  # chadburn.job-exec.{{ mautic_instance_name }}_dynamicscrm_integration_fetchleads.command:
  #   "{{ mautic_console }} mautic:integration:fetchleads -i Dynamics"
  # chadburn.job-exec.{{ mautic_instance_name }}_dynamicscrm_integration_fetchleads.user: "www-data"
