---
# General variables

# The base stack name, change this if you want to deploy multiple instances on the same host.
mautic_instance_name: mautic

# Set this to true to enable logging even of possible sensitive information
mautic_setup_force_log: false

# Set this to true to force container pull on every mautic_setup_all run
# Hint: mautic_update already enforces container pull on every run
mautic_force_container_pull: false

# Mautic application settings
mautic_install_source: "docker"
mautic_trusted_proxies: '["127.0.0.1"]'
mautic_site_url: "http://{{ mautic_instance_name }}.local:{{ mautic_httpd_port }}"
# Database settings
mautic_db_driver: "pdo_mysql"
mautic_db_table_prefix: ""
mautic_db_name: "{{ mautic_instance_name }}"
mautic_db_user: "{{ mautic_instance_name }}"
mautic_db_user_secret: my_secret
mautic_db_root_secret: my_secret

# Docker networks
mautic_network_backend: "{{ mautic_instance_name }}-net"
# ToDo: traefik network should be defined elsewhere
mautic_network_frontend: "traefik_dev_network"

# Mautic service container
mautic_app_image_name: "ghcr.io/netresearch/mautic"
mautic_app_image_tag: "4.2-php7.4"
mautic_app_storage_container: "/var/www/html"
mautic_app_env:
  MAUTIC_DB_HOST: "{{ mautic_dbms_service_name }}"
  MAUTIC_DB_USER: "{{ mautic_db_user }}"
  MAUTIC_DB_PASSWORD: "{{ mautic_db_user_secret }}"
  MAUTIC_DB_NAME: "{{ mautic_db_name }}"
  MAUTIC_INSTALL_SOURCE: "{{ mautic_install_source }}"
  MAUTIC_DB_DRIVER: "{{ mautic_db_driver }}"
  MAUTIC_DB_TABLE_PREFIX: "{{ mautic_db_table_prefix }}"
  MAUTIC_TRUSTED_PROXIES: "{{ mautic_trusted_proxies | string }}"
  MAUTIC_SITE_URL: "{{ mautic_site_url }}"

# HTTPD service
mautic_httpd_image_name: "{{ mautic_app_image_name }}"
mautic_httpd_image_tag: "{{ mautic_app_image_tag }}"
mautic_httpd_port: "80"
mautic_httpd_labels:

# DBMS service container
mautic_dbms_image_name: "mariadb"
mautic_dbms_image_tag: "10"
mautic_dbms_storage_container: "/var/lib/mysql"
mautic_dbms_env:
  MARIADB_DATABASE: "{{ mautic_db_name }}"
  MARIADB_USER: "{{ mautic_db_user }}"
  MARIADB_ROOT_PASSWORD: "{{ mautic_db_root_secret }}"
  MARIADB_PASSWORD: "{{ mautic_db_user_secret }}"
  MARIADB_AUTO_UPGRADE: "true"

# Cron service container
mautic_cron_image_name: "ghcr.io/premoweb/chadburn"
mautic_cron_image_tag: "latest"
mautic_cron_service_command: "daemon"

mautic_cron_command: "php {{ mautic_app_storage_container }}/bin/console --no-ansi --no-interaction"
mautic_cron_label_prefix: "chadburn.job-exec.{{ mautic_instance_name }}_"
mautic_cron_schedule_default: "@every 5m"
mautic_cron_user_default: "www-data"

mautic_app_cron:
  - name: "segments_update"
    command: "{{ mautic_cron_command }} mautic:segments:update"
  - name: "import"
    command: "{{ mautic_cron_command }} mautic:import"
  - name: "campaigns_update"
    command: "{{ mautic_cron_command }} mautic:campaigns:update"
  - name: "campaigns_trigger"
    command: "{{ mautic_cron_command }} mautic:campaigns:trigger"
  - name: "messages_send"
    command: "{{ mautic_cron_command }} mautic:messages:send"
  - name: "emails_send"
    command: "{{ mautic_cron_command }} mautic:emails:send"
  - name: "email_fetch"
    command: "{{ mautic_cron_command }} mautic:email:fetch"
  - name: "social_monitoring"
    command: "{{ mautic_cron_command }} mautic:social:monitoring"
  - name: "webhooks_process"
    command: "{{ mautic_cron_command }} mautic:webhooks:process"
  - name: "broadcasts_send"
    command: "{{ mautic_cron_command }} mautic:broadcasts:send"
  - name: "maintenance_cleanup"
    schedule: "5 */24 * * *"
    command: "{{ mautic_cron_command }} mautic:maintenance:cleanup --days-old=365"
  - name: "iplookup_download"
    schedule: "15 */240 * * *"
    command: "{{ mautic_cron_command }} mautic:iplookup:download"
  - name: "reports_scheduler"
    command: "{{ mautic_cron_command }} mautic:reports:scheduler"
  - name: "unusedip_delete"
    schedule: "30 */240 * * *"
    command: "{{ mautic_cron_command }} mautic:unusedip:delete"
  # # ENABLES HUBSPOT CRON
  # - name: "hubspot_integration_fetchleads"
  #   schedule: "10,40 * * * *"
  #   command: "{{ mautic_cron_command }} mautic:integration:fetchleads --integration=Hubspot"
  # - name: "hubspot_integration_pushactivity"
  #   schedule: "15,45 * * * *"
  #   command: "{{ mautic_cron_command }} mautic:integration:pushactivity --integration=Hubspot"
  # # ENABLES SALESFORCE CRON
  # - name: "salesforce_integration_fetchleads"
  #   schedule: "10,40 * * * *"
  #   command: "{{ mautic_cron_command }} mautic:integration:fetchleads --integration=Salesforce"
  # - name: "salesforce_integration_pushactivity"
  #   schedule: "12,42 * * * *"
  #   command: "{{ mautic_cron_command }} mautic:integration:pushactivity --integration=Salesforce"
  # - name: "salesforce_integration_pushleadactivity"
  #   schedule: "14,44 * * * *"
  #   command: "{{ mautic_cron_command }} mautic:integration:pushleadactivity --integration=Salesforce"
  # - name: "salesforce_integration_synccontacts"
  #   schedule: "16,46 * * * *"
  #   command: "{{ mautic_cron_command }} mautic:integration:synccontacts --integration=Salesforce"
  # # ENABLES SUGARCRM CRON
  # - name: "sugarcrm_integration_fetchleads"
  #   schedule: "10,40 * * * *"
  #   command: "{{ mautic_cron_command }} mautic:integration:fetchleads --fetch-all --integration=Sugarcrm"
  # # ENABLES PIPEDRIVE CRON
  # - name: "pipedrive_integration_fetch"
  #   schedule: "10,40 * * * *"
  #   command: "{{ mautic_cron_command }} mautic:integration:pipedrive:fetch"
  # - name: "pipedrive_integration_push"
  #   schedule: "15,45 * * * *"
  #   command: "{{ mautic_cron_command }} mautic:integration:pipedrive:push"
  # # ENABLES ZOHO CRON
  # - name: "zohocrm_integration_fetchleads"
  #   schedule: "10,40 * * * *"
  #   command: "{{ mautic_cron_command }} mautic:integration:fetchleads --integration=Zoho"
  # # ENABLES DYNAMICS CRON
  # - name: "dynamicscrm_integration_fetchleads"
  #   schedule: "10,40 * * * *"
  #   command: "{{ mautic_cron_command }} mautic:integration:fetchleads -i Dynamics"

mautic_app_labels:
  - label: "chadburn.enabled"
    value: "true"
  - label: "chadburn.no-overlay"
    value: "true"
