---

mautic_app_volume_name: "{{ mautic_instance_name }}_app_data"
mautic_app_image: "{{ mautic_app_image_name }}:{{ mautic_app_image_tag }}"
# must match upstream host name in httpd config (nginx)
mautic_app_service_name: "{{ mautic_instance_name }}"
mautic_app_mounts:
  - source: "{{ mautic_app_volume_name }}"
    target: "{{ mautic_app_storage_container }}"
    type: volume

mautic_httpd_image: "{{ mautic_httpd_image_name }}:{{ mautic_httpd_image_tag }}"
mautic_httpd_service_name: "{{ mautic_instance_name }}_httpd"
mautic_httpd_mounts: "{{ mautic_app_mounts }}"

mautic_dbms_volume_name: "{{ mautic_instance_name }}_dbms_data"
mautic_dbms_image: "{{ mautic_dbms_image_name }}:{{ mautic_dbms_image_tag }}"
mautic_dbms_service_name: "{{ mautic_instance_name }}_dbms"
mautic_dbms_mounts:
  - source: "{{ mautic_dbms_volume_name }}"
    target: "{{ mautic_dbms_storage_container }}"
    type: volume

mautic_cron_image: "{{ mautic_cron_image_name }}:{{ mautic_cron_image_tag }}"
mautic_cron_service_name: "{{ mautic_instance_name }}_cron"


mautic_message_no_update_available:
  "Great! You are running the current version of Mautic."
