---
- name: Mautic | Pull cron container image
  community.docker.docker_image:
    name: "{{ mautic_cron_image }}"
    source: pull
    force_source: "{{ mautic_force_container_pull }}"
  register: image_output

- name: Mautic | Start cron container
  community.docker.docker_container:
    name: "{{ mautic_cron_service_name }}"
    image: "{{ mautic_cron_image }}"
    state: started
    detach: true
    mounts:
      - source: "/var/run/docker.sock"
        target: "/var/run/docker.sock"
        read_only: true
        type: bind
    restart_policy: unless-stopped
    command: "{{ mautic_cron_service_command }}"
  register: mautic_cron_status
  ignore_errors: '{{ ansible_check_mode }}'
  no_log: "{{ mautic_setup_force_log == false }}"
  diff: "{{ mautic_setup_force_log }}"
