---
- name: Mautic | Pull application container image
  community.docker.docker_image:
    name: "{{ mautic_app_image }}"
    source: pull
    force_source: "{{ mautic_force_container_pull }}"
  register: image_output

- name: Mautic | Wait until database container is up and healthy
  community.docker.docker_container_info:
    name: "{{ mautic_dbms_service_name }}"
  register: result
  until: result.container is search("healthy")
  retries: 10
  delay: 10
  when: not ansible_check_mode | bool

- name: Clear labels
  ansible.builtin.set_fact:
    mautic_app_labels_rendered: {}

# do not use 6-piece schedules (5-59/5 * * * * *), because of:
# https://github.com/PremoWeb/chadburn/issues/13
# use only 5-piece schedules (5-59/5 * * * *)
- name: Render labels for cron
  ansible.builtin.set_fact:
    mautic_app_labels_rendered:
      "{{
        mautic_app_labels_rendered
        | default({})
        | combine ({
            mautic_cron_label_prefix + item.name + '.command':
              item.command,
            mautic_cron_label_prefix + item.name + '.schedule':
              item.schedule|default(6|random|string + '-59/5 * * * *'),
            mautic_cron_label_prefix + item.name + '.user':
              item.user|default(mautic_cron_user_default)
        })
      }}"
  with_items: "{{ mautic_app_cron }}"

- name: Render other misc. labels
  ansible.builtin.set_fact:
    mautic_app_labels_rendered:
      "{{
        mautic_app_labels_rendered
        | default({})
        | combine ({ item.label : item.value })
      }}"
  with_items: "{{ mautic_app_labels }}"

- name: Mautic | Start application container
  community.docker.docker_container:
    name: "{{ mautic_app_service_name }}"
    image: "{{ mautic_app_image }}"
    state: started
    detach: true
    network_mode: "default"
    networks:
      - name: "{{ mautic_network_backend }}"
        aliases:
          - mautic
    env: "{{ mautic_app_env }}"
    mounts: "{{ mautic_app_mounts }}"
    labels: "{{ mautic_app_labels_rendered }}"
    container_default_behavior: no_defaults
    command: php-fpm
    command_handling: correct
    entrypoint: /usr/local/bin/entrypoint_mautic.sh
    restart_policy: unless-stopped
    comparisons:
      '*': strict
      labels: allow_more_present
  ignore_errors: "{{ ansible_check_mode }}"
  no_log: "{{ mautic_setup_force_log == false }}"
  diff: "{{ mautic_setup_force_log }}"
